import React, { useEffect, useMemo, useState } from "react";
import "./index.css";

const API = import.meta.env.VITE_API_URL || "http://localhost:8000";
function Chart({ points }) {
  const path = useMemo(() => points.map((p, i) => `${i ? "L" : "M"}${points.length === 1 ? 50 : i / (points.length - 1) * 100},${100 - p.confidence * 100}`).join(" "), [points]);
  return <div className="chart"><div><span>Model confidence</span><span>Review threshold: 70%</span></div>{points.length ? <svg viewBox="0 0 100 100" preserveAspectRatio="none"><line x1="0" y1="30" x2="100" y2="30"/><path d={path}/>{points.map((p,i)=><circle key={p.time+i} cx={points.length===1?50:i/(points.length-1)*100} cy={100-p.confidence*100} r="2.3" className={p.confidence>=.7?"alert":""}/>)}</svg> : <p>Run a demo to plot confidence.</p>}</div>;
}
function EventRow({ event }) {
  const title = event.type === "flag" ? event.reason : event.type === "followup" ? event.question : event.transcript || "Acoustic check";
  return <article className={`event ${event.type === "flag" ? "flag" : ""}`}><div className="event-top"><span className={`badge ${event.severity_label || "confirmed"}`}>{event.severity_label || event.type}</span><time>{new Date(event.time).toLocaleTimeString()}</time></div><strong>{title}</strong>{event.acoustic_label && <p>Acoustic: <b>{event.acoustic_label}</b> · confidence: {Math.round(event.confidence*100)}%{event.agreement === false && " · human/machine disagreement"}</p>}<div className="event-actions">{event.clip_url && <audio controls preload="none" src={`${API}${event.clip_url}`}/>} {event.type === "flag" && <a href={`${API}/events/${event.id}/report.pdf`} target="_blank" rel="noreferrer">Incident PDF</a>}</div></article>;
}
export default function App() {
  const [events,setEvents]=useState([]), [summary,setSummary]=useState({}), [trend,setTrend]=useState([]), [context,setContext]=useState({site_name:"Demo inspection",location:"Site A",worker_name:""}), [reason,setReason]=useState(""), [error,setError]=useState(""), [busy,setBusy]=useState(false);
  async function refresh(){try { const responses=await Promise.all(["/events","/events/summary","/events/confidence-trend","/inspection/context"].map(path=>fetch(API+path))); if(responses.some(r=>!r.ok)) throw Error(); const [e,s,t,c]=await Promise.all(responses.map(r=>r.json())); setEvents(e);setSummary(s);setTrend(t);setContext(c);setError(""); } catch {setError("Backend is unavailable. Start the API or check VITE_API_URL.");}}
  useEffect(()=>{refresh();const id=setInterval(refresh,4000);return()=>clearInterval(id)},[]);
  async function send(path,method="POST",body={}){setBusy(true);try{const r=await fetch(API+path,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!r.ok)throw Error();await refresh()}catch{setError("Could not save this inspection event.")}finally{setBusy(false)}}
  const flagCount=events.filter(e=>e.type==="flag").length;
  return <main className="app-shell"><header><div><p className="eyebrow">SITE EAR · LIVE INSPECTION</p><h1>Acoustic second opinion</h1><p className="subtitle">Evidence, confidence, and human judgment—cross-checked in one timeline.</p></div><div className={`status ${error?"offline":""}`}><i/> {error?"Backend offline":"Monitoring"}</div></header>{error&&<div className="error">{error}</div>}
  <section className="stats"><div><span>Checks</span><b>{summary.total_events||0}</b></div><div className="danger"><span>Flags</span><b>{flagCount}</b></div><div><span>Unresolved</span><b>{summary.unresolved||0}</b></div><div><span>Agreements</span><b>{summary.agreements||0}</b></div></section>
  <section className="grid"><div className="panel"><h2>Demo control room</h2><p>Run reliable, judge-ready inspection scenarios.</p><div className="buttons"><button disabled={busy} onClick={()=>send("/demo/mismatch")}>Run mismatch demo</button><button className="secondary" disabled={busy} onClick={()=>send("/demo/concern")}>Run concern demo</button></div><form onSubmit={e=>{e.preventDefault();if(reason.trim()){send("/events/flag","POST",{reason,confidence:.8,include_clip:true});setReason("")}}}><label>Supervisor manual flag</label><div className="inline"><input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Describe the issue"/><button disabled={busy||!reason.trim()}>Flag</button></div></form></div><div className="panel"><h2>Inspection identity</h2><p>Attach meaningful context to future reports.</p><form className="form" onSubmit={e=>{e.preventDefault();send("/inspection/context","PUT",context)}}>{[["site_name","Inspection name"],["location","Location"],["worker_name","Worker name"]].map(([key,label])=><input key={key} value={context[key]} onChange={e=>setContext({...context,[key]:e.target.value})} placeholder={label}/>)}<button disabled={busy}>Save details</button></form></div></section>
  <section className="panel"><h2>Confidence trend</h2><Chart points={trend}/></section><section className="panel timeline"><div className="heading"><div><h2>Inspection timeline</h2><p>{summary.summary_text||"Waiting for inspection."}</p></div><div className="actions"><a href={`${API}/events/export/csv`} download>Download CSV</a><a href={`${API}/events/export/json`} download>Download JSON</a></div></div>{events.length?[...events].reverse().map(e=><EventRow event={e} key={e.id}/>):<div className="empty">No events yet. Run the mismatch demo to create a complete evidence trail.</div>}</section></main>;
}
